Update meme

diff --git a/meme b/meme
--- a/meme
+++ b/meme
@@ -1,8 +1,43 @@
 #!/usr/bin/bash
 # Author: HAKXCORE https://github.com/hakxcore
+#Colors
+currentVersion="2.1.3"
+RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')" 
+MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')"  BLACK="$(printf '\033[30m')"  
+REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"  
+MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')"  BLACKBG="$(printf '\033[40m')" 
+RESETBG="$(printf '\e[0m')"  BLINK="$(printf '\033[5;31m')"
 
-currentVersion="1.2.0"
 configuredClient=""
+
+##Platform Check
+if [[ "$OSTYPE" == linux-android* ]]; then
+  distro="termux"
+  platform="Termux"
+  prefix="/data/data/com.termux/files/"
+  SUDO=""
+fi
+
+if [ -z "$distro" ]; then
+  distro=$(ls /etc | awk 'match($0, "(.+?)[-_](?:release|version)", groups) {if(groups[1] != "os") {print groups[1]}}')
+  platform="Debian"
+  prefix=""
+  SUDO="sudo"
+fi
+
+if [ -z "$distro" ]; then
+  if [ -f "/etc/os-release" ]; then
+    distro="$(source /etc/os-release && echo $ID)"
+  elif [ "$OSTYPE" == "darwin" ]; then
+    distro="darwin"
+    platform="Darwin"
+    prefix=""
+    SUDO="sudo"
+  else 
+    distro="invalid"
+  fi
+fi
+
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
@@ -20,6 +55,28 @@ getConfiguredClient()
   fi
 }
 
+##determines weather jp2a is installed or not
+getConfiguredjp2a()
+{
+        if command -v jp2a &>/dev/null; then
+                configuredjp2a="jp2a"
+        else
+                echo "This tool needs jp2a to be installed"
+                echo $RED"Use $STRONG"apt install jp2a"$RED to install jp2a firstly$RESETBG"
+	fi
+}
+
+##determines weather pv package is installed or not
+getConfiguredpv()
+{
+        if command -v pv &>/dev/null; then
+                configuredpv="pv"
+        else
+                echo "This tool needs pv to be installed"
+                echo $RED"Use $STRONG"apt install pv"$RED to install pv firstly$RESETBG"
+	fi
+}
+
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
@@ -30,19 +87,20 @@ httpGet()
     fetch) fetch -q "$@" ;;
   esac
 }
+
+##This function Checks for the insternet connectivity
 checkInternet()
 {
   httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
 }
+
+##This function determines the latest version of the termux-snippets if available and installs them
 update()
 {
-  # Author: HAKXCORE https://github.com/hakxcore
-  # Update utility version
-  # To test the tool enter in the defualt values that are in the examples for each variable
   currentVersion=$currentVersion
-  repositoryName="legendary-meme" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="hakxcore" #username that hosts the repostiory ex. hakxcore
-  nameOfInstallFile="install" # change this if the installer file has a different name be sure to include file extension if there is one
+  repositoryName="termux-snippets" 
+  githubUserName="hakxcore" 
+  nameOfInstallFile="install" 
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
   if [ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]; then
@@ -58,7 +116,7 @@ update()
       read -r answer
       if [ "$answer" == [Yy] ]; then
         cd ~ || { echo 'Update Failed'; exit 1; }
-        if [ -d  ~/$repositoryName ]; then rm -rf $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        if [ -d  ~/$repositoryName ]; then rm -rf $repositoryName || { echo "Permissions Error: try running the update again"; exit 1; } ; fi
         echo -n "Downloading latest version of: $repositoryName."
         git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .TSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
         while [ ! -f .TSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
@@ -66,10 +124,9 @@ update()
         echo "Success!"
         cd $repositoryName || { echo 'Update Failed'; exit 1; }
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
-        ./$nameOfInstallFile "update" || exit 1
+        $SUDO ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory again"; exit 1; }
       else
         exit 1
       fi
@@ -79,6 +136,7 @@ update()
   fi
 }
 
+##Backgrounds to use for memes
 backGrounds()
 {
   cat <<EOF
@@ -117,8 +175,11 @@ backGrounds()
 EOF
 }
 
+##Main function
 main(){
-    python3 banner/banner.py
+    clear
+    getConfiguredjp2a
+    getConfiguredpv
     echo -en "\e[1;2;32m Enter the name for the meme's background (Ex. buzz, doge, blb ): \e[0m"
     read bg
     echo -en "\e[1;2;32m Enter text for first line: \e[0m"
@@ -129,8 +190,8 @@ main(){
     read raw_second
     almost_second=$(echo "$raw_second" | awk '{print tolower($0)}')
     second=$(echo "$almost_second" | sed -e 's/ /_/g')
-    echo -en "\e[1;2;32m Choose any random digit between[0..20]: \e[0m"
-    read num
+    #curl -s "https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new"| read num
+    num=$RANDOM
     if [ -z "$first" ]
     then
     first=$(echo "_")
@@ -143,69 +204,78 @@ main(){
     else
       echo ""
     fi
-    echo -e "\e[1;2;32m ------------------------GENRATING MEME FOR YOU----------------------------\e[0m"
-    echo -e "\033[31m"
-    curl "https://api.memegen.link/images/$bg/$first/$second.png" >> $fileName$num.png || return 1
-    echo "\e[0m"
-    echo -e "\e[1;2;32m ----------------------MEME SUCCESSFULLY GENRATED--------------------------\e[0m"
+    echo -e "\e[1;2;32m ----------------------------GENRATING MEME FOR YOU--------------------------------\e[0m"
+    curl -s "https://api.memegen.link/images/$bg/$first/$second.jpeg" >> $fileName$num.jpeg || return 1
+    if [ -d "Meme" ]
+    then
+      echo "-"
+    else
+    mkdir Meme
+  fi
+    mv $fileName$num.jpeg Meme
+    echo -en "\e[1;2;32m Meme stored in Meme Folder\e[0m"
     echo ""
-    mv $fileName$num.png output
-    echo -en "\e[1;2;32m Meme stored in output Folder\e[0m"
+    jp2a Meme/$fileName$num.jpeg | pv -qL 15
     echo ""
-    echo -en "\e[1;2;32m Do you wanna open it[y/n]: \e[0m"
+    xdg-open Meme/$fileName$num.jpeg 
+    echo -e "\e[1;2;32m --------------------------MEME SUCCESSFULLY GENRATED------------------------------\e[0m"
+    echo ""
+    echo -en "\e[1;2;32m Do you wanna Delete it[y/n]: \e[0m"
     read choice
     if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
-	    xdg-open output/$fileName$num.png
-    fi	    
+            rm -rf Meme/$fileName$num.jpeg
+    fi
     return 0
 }
 
+
+##Usage and Help
 usage()
 {
   cat <<EOF
+
 Meme
-Description: A lightning fast meme generator
-Usage: ./meme [flags] or ./meme
-  -d  See all Backgrouds for meme
-  -u  Update legendary-meme you can use [update] also
-  -h  Show the help you can use [help] also
-  -v  Get the tool version you can use [version] also
+
+Description: A lightning fast meme generator from terminal.
+
+Usage: meme [flags] or meme
+  -b  See all Backgrouds
+  -u  Update Termux-snippets you can use [update] also
+  -h  Show help you can use [help] also
+  -v  Tool version you can use [version] also
+
 Examples:
-   ./meme #Thats it
-   ./meme -h or ./meme -help #For help
-   ./meme -d #For all backgrounds
-   ./meme -v #For version
+   meme
 EOF
 }
 
-
-
-while getopts "b:f:uvhd" opt; do
+##Options(flags)
+while getopts "d:f:uvhb" opt; do
   case "$opt" in
     \?) echo "Invalid option: -$OPTARG" >&2
         exit 1
         ;;
 #######################These flags will be updated later########################
-  b)
-		bg=${OPTARG}
-		;;
-	f)
-		raw_first=${OPTARG}
-		almost_first=$(echo "$raw_first" | awk '{print tolower($0)}')
-    	first=$(echo "$almost_first" | sed -e 's/ /_/g')
-    	;;
+  d)
+                bg=${OPTARG}
+                ;;
+        f)
+                raw_first=${OPTARG}
+                almost_first=$(echo "$raw_first" | awk '{print tolower($0)}')
+        first=$(echo "$almost_first" | sed -e 's/ /_/g')
+        ;;
     s)
-		raw_second=${OPTARG}
-		almost_second=$(echo "$raw_second" | awk '{print tolower($0)}')
-    	second=$(echo "$almost_second" | sed -e 's/ /_/g')
-    	;;
+                raw_second=${OPTARG}
+                almost_second=$(echo "$raw_second" | awk '{print tolower($0)}')
+        second=$(echo "$almost_second" | sed -e 's/ /_/g')
+        ;;
     f)
         fileName=${OPTARG}
         getConfiguredClient || exit 1
         checkInternet || exit 1
         main || exit 1
         exit 0
-    	;;
+        ;;
 ##############################################################################
     h)  usage
         exit 0
@@ -218,7 +288,7 @@ while getopts "b:f:uvhd" opt; do
         update
         exit 0
         ;;
-    d)
+    b)
         backGrounds
         exit 0
         ;;
@@ -229,19 +299,19 @@ while getopts "b:f:uvhd" opt; do
   esac
 done
 
-# special set of first arguments that have a specific behavior across tool
+# special set of first arguments that have a specific behavior across tools
 if [ "$fileName" == "" ]; then
-	fileName="meme"
-	main || exit 1
-	exit 0
+        fileName="meme"
+        main || exit 1
+        exit 0
 fi
-
+##Driver
 if [ "$1" == "update" ]; then
-	getConfiguredClient || exit 1
-	checkInternet || exit 1
-	update || exit 1
-	exit 0
+        getConfiguredClient || exit 1
+        checkInternet || exit 1
+        update || exit 1
+        exit 0
 elif [ "$1" == "help" ]; then
-	usage
-	exit 0
+        usage
+        exit 0
 fi
